package catalog

const (
	POINT = "POINT"
	MULTIPOINT = "MULTIPOINT"

	POLYGON = "POLYGON"
	MULTIPOLYGON = "MULTIPOLYGON"

	LINESTRING = "LINESTRING"
	MULTILINESTRING = "MULTILINESTRING"

	GEOMETRY = "GEOMETRY"
	GEOMETRYCOLLECTION = "GEOMETRYCOLLECTION"
)
