package config

const (
	//General settings
	LOG_LEVEL        = "LOG_LEVEL"

	//server settings
	SERVER_PORT string = "PORT"
	SERVER_DEBUG = "DEBUG"
	SERVER_HEALTHCHECK = "HEALTH_CHECK"
	SERVER_HEALTHCHECK_PATH = "HEALTH_CHECK_PATH"

	SERVER_OVERRIDE_REQUESTED_HOST = "SERVER_OVERRIDE_REQUESTED_HOST"
	SERVER_PROTO = "SERVER_PROTO"
	SERVER_HOSTNAME = "SERVER_HOSTNAME"
	SERVER_ADVERTISE_PORT = "SERVER_ADVERTISE_PORT"
	//ssl
	SSL_ENABLE = "SSL_ENABLE"
	SSL_KEYFILE = "SSL_KEYFILE"
	SSL_CERTFILE = "SSL_CERTFILE"

	//database settings
	POSTGRES_PORT = "PGPORT"
	POSTGRES_HOST = "PGHOST"
	POSTGRES_DATABASE = "PGDATABASE"
	POSTGRES_USER = "PGUSER"
	POSTGRES_PASSWORD = "PGPASSWORD"
	POSTGRES_FAILFAST = "POSTGRES_FAILFAST"

	POSTGRES_READONLY = "POSTGRES_READONLY"




)


